config/routes.rb
Rails.application.routes.draw do
  get '/flats', to: 'flats#index', as: :flats
  get '/flats/:id', to: 'flats#show', as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'json'
require 'open-uri'

class FlatsController < ApplicationController
	URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"

	before_action :set_flats

	def index; end

	def show
		@flat = @flats.find { |flat| flat['id'] === params['id'].to_i }
	end

	def set_flats
		@flats = JSON.parse(URI.open(URL).read)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>

<% @flats.each do |flat| %>
	<%= link_to flat_path(flat['id']) do %>
		<%= image_tag flat.dig('imageUrl'), width: 400 %>
		<p>
			<strong>
				<%= flat.dig('name') %>
			</strong> -
			<%= flat.dig('price') %>
		</p>
	<% end %>
<% end %>

app/views/flats/show.html.erb
<%= link_to 'Go to flats', flats_path, style: 'display: block;' %>

<%= image_tag @flat['imageUrl'] %>

<h1>
	<%= @flat['name'] %>
</h1>

<p>
	<%= @flat['price'] %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>